name: CI - RFM Cluster Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Clonar repositório
      uses: actions/checkout@v3

    - name: 🐍 Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: 📦 Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: ✅ Verificar sintaxe dos scripts
      run: |
        python -m py_compile exportar_rfm_com_clusters.py dashboard_rfm.py
